DROP TABLE IF EXISTS ARTIST_GALLERY;
DROP TABLE IF EXISTS ART;
DROP TABLE IF EXISTS GALLERY;
DROP TABLE IF EXISTS ARTIST;

CREATE TABLE ARTIST (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    "NAME" TEXT,
    GENRE TEXT
);

CREATE TABLE ART (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TITLE TEXT,
    THEME TEXT,
    ARTISTID INT,
    FOREIGN KEY (ARTISTID) REFERENCES ARTIST(ID)
);

CREATE TABLE GALLERY (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    "NAME" TEXT,
    "LOCATION" TEXT
);

CREATE TABLE ARTIST_GALLERY (
    ARTISTID INTEGER,
    GALLERYID INTEGER,
    PRIMARY KEY (ARTISTID, GALLERYID),
    FOREIGN KEY (ARTISTID) REFERENCES ARTIST(ID),
    FOREIGN KEY (GALLERYID) REFERENCES GALLERY(ID) 
);